import type { Video, Creator } from "@/types";

// Rich mock creators with diverse drag personas
export const mockCreators: Creator[] = [
  {
    did: "did:plc:z72i7hdynmk6r22z27h6tvur1",
    handle: "diamonddust",
    displayName: "Diamond Dust",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Diamond&backgroundColor=c0aede&hairColor=b48b59",
    description: "Drag artist, choreographer & content creator 💎✨ | LA/NYC | Shows every weekend",
    followerCount: 145200,
    followingCount: 892,
    createdAt: new Date("2023-01-15"),
    verified: true,
  },
  {
    did: "did:plc:bv5t4h3j8k2m1n9p0q8r7s6t2",
    handle: "phoenixfire",
    displayName: "Phoenix Fire",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Phoenix&backgroundColor=f5a6d3&hairColor=d84242",
    description: "Drag King 👑 | Performer | Host | Chicago nightlife royalty",
    followerCount: 82340,
    followingCount: 654,
    createdAt: new Date("2022-06-20"),
    verified: true,
  },
  {
    did: "did:plc:k9j8l7m6n5o4p3q2r1s0t9u3",
    handle: "lunastarlight",
    displayName: "Luna Starlight",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Luna&backgroundColor=fdbcb4&hairColor=724133",
    description: "Baby queen making waves 🌙✨ | ATL | Booking info in bio",
    followerCount: 23500,
    followingCount: 2341,
    createdAt: new Date("2024-03-10"),
    verified: false,
  },
  {
    did: "did:plc:m8n7o6p5q4r3s2t1u0v9w8x4",
    handle: "sapphirestorm",
    displayName: "Sapphire Storm",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sapphire&backgroundColor=a6e3f5&hairColor=65c9ff",
    description: "Queen of ballroom 💙 | Vogue femme legend | NYC based",
    followerCount: 198700,
    followingCount: 1243,
    createdAt: new Date("2021-09-12"),
    verified: true,
  },
  {
    did: "did:plc:x7y6z5a4b3c2d1e0f9g8h7i5",
    handle: "rubydanger",
    displayName: "Ruby Danger",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Ruby&backgroundColor=ffc0cb&hairColor=e16381",
    description: "Comedy queen 💋 Roast battle champion | SF Bay Area",
    followerCount: 67890,
    followingCount: 445,
    createdAt: new Date("2023-05-22"),
    verified: true,
  },
  {
    did: "did:plc:p9q8r7s6t5u4v3w2x1y0z9a6",
    handle: "emeraldenvy",
    displayName: "Emerald Envy",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Emerald&backgroundColor=90ee90&hairColor=0ba360",
    description: "Fashion forward 💚 | Costume designer | Miami nightlife",
    followerCount: 54320,
    followingCount: 789,
    createdAt: new Date("2023-11-08"),
    verified: false,
  },
];

// Rich mock videos with diverse drag content
export const mockVideos: Video[] = [
  {
    id: "vid_001",
    title: "Full Beat in 20 Minutes - Club Kid Realness",
    description: "Watch me transform from boy to SICKENING in under 20 minutes! Products used: NYX Epic Ink Liner, Morphe 35B palette, Ben Nye translucent powder. Full product list in the description! 💄✨",
    thumbnail: "https://picsum.photos/seed/makeup1/640/360",
    duration: 1247,
    views: 234500,
    likes: 18923,
    createdAt: new Date("2025-01-12"),
    playbackUrl: "https://example.com/videos/makeup-tutorial.m3u8",
    livepeerAssetId: "asset_makeup_1",
    contentType: "long",
    creator: mockCreators[0],
    category: "Beauty & Makeup",
    tags: ["makeup", "drag", "tutorial", "beauty", "transformation"],
  },
  {
    id: "vid_002",
    title: "OBSESSED - Mariah Carey Lip Sync",
    description: "Why you so obsessed with me? 💋 This performance from last night's show had everyone GAGGING",
    thumbnail: "https://picsum.photos/seed/lipsync1/640/360",
    duration: 45,
    views: 562000,
    likes: 42563,
    createdAt: new Date("2025-01-13"),
    playbackUrl: "https://example.com/videos/lipsync-short.m3u8",
    livepeerAssetId: "asset_short_1",
    contentType: "short",
    creator: mockCreators[1],
    category: "Entertainment",
    tags: ["lipsync", "mariah", "performance", "dragshow"],
  },
  {
    id: "vid_003",
    title: "The Real Tea Ep 12: Drag Race All Stars Drama",
    description: "Serving you ALL the tea on this week's All Stars episode! Guest: Sapphire Storm talks about her elimination and backstage drama. Timestamps in comments! ☕",
    thumbnail: "https://picsum.photos/seed/podcast1/640/360",
    duration: 3456,
    views: 145000,
    likes: 8234,
    createdAt: new Date("2025-01-11"),
    playbackUrl: "https://example.com/videos/podcast-1.m3u8",
    livepeerAssetId: "asset_podcast_1",
    contentType: "podcast",
    creator: mockCreators[2],
    category: "Entertainment",
    tags: ["podcast", "dragrace", "tea", "interview"],
  },
  {
    id: "vid_004",
    title: "ELECTRIC DREAMS - Original Music Video",
    description: "My debut single is OUT NOW! 🎵⚡ Directed by @phoenixfire, choreography by the house of Xtravaganza. Stream on all platforms!",
    thumbnail: "https://picsum.photos/seed/music1/640/360",
    duration: 245,
    views: 892400,
    likes: 67890,
    createdAt: new Date("2025-01-09"),
    playbackUrl: "https://example.com/videos/summer-bop.m3u8",
    livepeerAssetId: "asset_music_1",
    contentType: "music",
    creator: mockCreators[0],
    category: "Music",
    tags: ["music", "original", "musicvideo", "pop"],
  },
  {
    id: "vid_005",
    title: "Vogue Femme Tutorial: The Basics",
    description: "Learn the fundamentals of vogue femme! Hand performance, catwalk, duckwalk, floor performance & dips. Perfect for beginners! 💃",
    thumbnail: "https://picsum.photos/seed/dance1/640/360",
    duration: 892,
    views: 178900,
    likes: 12456,
    createdAt: new Date("2025-01-10"),
    playbackUrl: "https://example.com/videos/vogue-tutorial.m3u8",
    livepeerAssetId: "asset_dance_1",
    contentType: "long",
    creator: mockCreators[3],
    category: "Dance",
    tags: ["vogue", "ballroom", "tutorial", "dance"],
  },
  {
    id: "vid_006",
    title: "Reading is FUNDAMENTAL - Stand Up Set",
    description: "Best of my comedy roast from The Laugh Factory! Warning: NSFW and absolutely SAVAGE 🔥😂",
    thumbnail: "https://picsum.photos/seed/comedy1/640/360",
    duration: 678,
    views: 445600,
    likes: 28934,
    createdAt: new Date("2025-01-08"),
    playbackUrl: "https://example.com/videos/comedy-set.m3u8",
    livepeerAssetId: "asset_comedy_1",
    contentType: "long",
    creator: mockCreators[4],
    category: "Comedy",
    tags: ["comedy", "roast", "standup", "reading"],
  },
  {
    id: "vid_007",
    title: "DIY Drag on a Budget: $50 Lewk Challenge",
    description: "Creating a FULL drag look for under $50! Thrifted outfit, drugstore makeup, and homemade jewelry. Proof you don't need coin to serve looks! 👗✨",
    thumbnail: "https://picsum.photos/seed/fashion1/640/360",
    duration: 1034,
    views: 267800,
    likes: 19876,
    createdAt: new Date("2025-01-07"),
    playbackUrl: "https://example.com/videos/budget-fashion.m3u8",
    livepeerAssetId: "asset_fashion_1",
    contentType: "long",
    creator: mockCreators[5],
    category: "Fashion",
    tags: ["fashion", "diy", "budget", "thrifted"],
  },
  {
    id: "vid_008",
    title: "Death Drop Tutorial - DON'T Break Your Spine!",
    description: "The SAFE way to learn death drops! Proper technique, stretches, and progressions. 30 seconds of fabulousness!",
    thumbnail: "https://picsum.photos/seed/deathdrop1/640/360",
    duration: 30,
    views: 789000,
    likes: 56234,
    createdAt: new Date("2025-01-13"),
    playbackUrl: "https://example.com/videos/death-drop.m3u8",
    livepeerAssetId: "asset_short_2",
    contentType: "short",
    creator: mockCreators[3],
    category: "Dance",
    tags: ["deathdrop", "tutorial", "performance", "dragmoves"],
  },
  {
    id: "vid_009",
    title: "Wig Styling 101: Lace Front Installation",
    description: "Everything you need to know about lace front wigs! Cutting the lace, adhesive application, blending, and styling tips. Products linked below!",
    thumbnail: "https://picsum.photos/seed/wig1/640/360",
    duration: 967,
    views: 312400,
    likes: 15678,
    createdAt: new Date("2025-01-06"),
    playbackUrl: "https://example.com/videos/wig-tutorial.m3u8",
    livepeerAssetId: "asset_beauty_2",
    contentType: "long",
    creator: mockCreators[0],
    category: "Beauty & Makeup",
    tags: ["wigs", "tutorial", "beauty", "hairstyling"],
  },
  {
    id: "vid_010",
    title: "Behind the Scenes: Pride Parade Prep",
    description: "Getting ready for LA Pride! Watch me prep costumes, do makeup, and get emotional about what Pride means to me 🌈💖",
    thumbnail: "https://picsum.photos/seed/pride1/640/360",
    duration: 1456,
    views: 423100,
    likes: 34567,
    createdAt: new Date("2025-01-05"),
    playbackUrl: "https://example.com/videos/pride-bts.m3u8",
    livepeerAssetId: "asset_vlog_1",
    contentType: "long",
    creator: mockCreators[1],
    category: "Entertainment",
    tags: ["pride", "vlog", "bts", "lgbtq"],
  },
  {
    id: "vid_011",
    title: "Runway Walk Masterclass",
    description: "Serve FACE, serve BODY! Learn the art of the runway walk with tips from pageant legend Diamond Dust 👠",
    thumbnail: "https://picsum.photos/seed/runway1/640/360",
    duration: 723,
    views: 198700,
    likes: 11234,
    createdAt: new Date("2025-01-11"),
    playbackUrl: "https://example.com/videos/runway.m3u8",
    livepeerAssetId: "asset_tutorial_1",
    contentType: "long",
    creator: mockCreators[0],
    category: "Fashion",
    tags: ["runway", "pageant", "tutorial", "modeling"],
  },
  {
    id: "vid_012",
    title: "60 Seconds of CHAOS - Drag Fails Compilation",
    description: "When drag goes WRONG! Wigs flying, heels breaking, makeup malfunctions. We're laughing at ourselves! 😂",
    thumbnail: "https://picsum.photos/seed/fails1/640/360",
    duration: 60,
    views: 1234500,
    likes: 89012,
    createdAt: new Date("2025-01-12"),
    playbackUrl: "https://example.com/videos/fails.m3u8",
    livepeerAssetId: "asset_short_3",
    contentType: "short",
    creator: mockCreators[4],
    category: "Comedy",
    tags: ["comedy", "fails", "funny", "bloopers"],
  },
];

export const categories = [
  "All",
  "Entertainment",
  "Beauty & Makeup",
  "Music",
  "Comedy",
  "Dance",
  "Fashion",
];
